const DEBUG = false;

/**
 * This script generates agenda notes for 1:1 meetings.
 * It created the content for a 1:1 meeting based on sections kept on an object in code
 * and topics for each week kept in a spreadsheet.
 * It search for recurrences in the calendar and if there is a meeting scheduled,
 * the document is update with the agenda.
 * 
 * Next:
 * - Once the agenda is added, add a comment to tag the person
 */

// Set up the required constants
const CALENDAR_ID = PropertiesService.getScriptProperties().getProperty(calendarId);
const TOPICS_SHEET_ID = PropertiesService.getScriptProperties().getProperty(spreadsheetId);
const SETTINGS_DOC_ID = PropertiesService.getScriptProperties().getProperty(spreadsheetId);
const SETTINGS_SHEET_NAME = 'settings';

const AGENDA_SECTIONS = [
  {
    title: "Wins",
    description: "What are you proud of? Any highlights from last week? From specs and PRs, anything that you came up with a good solution or helped to spot a possible problem?"
  },
  {
    title: "Solving problems",
    description: "What is on your plate? Anything blocking you? Do you need any support? How can I help you?",
    nest: [
      {
        title: "Scrum Board.",
        url: "https://jira.cfdata.org/secure/RapidBoard.jspa?projectKey=FLPROTO&rapidView=5117"
      }
    ]
  },
  {
    title: "Stack",
    description: "What would you like to talk about today?",
  },
  {
    title: "Career & Grow",
    description: "How are you progressing with your current objectives and personal development goals?"
  },
  {
    title: "Feedback",
    description: "How can we do better? Highlights or recognitions for the team?",
  },
  {
    title: "Action items"
  }
];

// Document format settings
const orange = '#ff9900';
const black = "#000000";

/**
 * The main function
 */
function run() {
  const week = getWeekDates(PropertiesService.getScriptProperties().getProperty(period));
  const oneToOneEvents = getOneToOneEvents(SETTINGS_DOC_ID, SETTINGS_SHEET_NAME);
  const eventsToProcess = getEvents(week.start, week.end, oneToOneEvents);
  const topicsToProcess = getTopicsToProcess(TOPIC_SHEET_ID,PropertiesService.getScriptProperties().getProperty(year),week.number);

  eventsToProcess.forEach(event => {
    addMeetingNotesToDoc(event.calendarEvent, event.settings.targetDoc, topicsToProcess);
    sendNotification(event.calendarEvent, event.settings.targetDoc);
  })
}



/**
 * Send email notification with link to the document
 * @todo make the type of email to send configurable, at the moment is two different functions, one for all and another just for creator
 * 
 * @param event google class CalendarEvent
 * @param targetDocId The id of the agenda google document
 */
function sendNotification(event, targetDocId) {
  const emailProperties = {};

  const formattedDate = Utilities.formatDate(event.getStartTime(),'GMT','yyyy-MM-dd');
  emailProperties.subject = `[Action required] The agenda for ${formattedDate} | ${event.getTitle()} is ready`;

  const targetDocLink = `https://docs.google.com/document/d/${targetDocId}`;

  emailProperties.message = "<p>I'm looking forward for our 1:1 on " + formattedDate + "</p>" +
                            "<p>Please take some time to review and add content to the agenda in " + targetDocLink + "</p><br>" +
                            "<p style=\"font-style: italic;\">This email was <a href=\"https://github.com/nmicht/automate-1to1-agenda\">autogenerated</a></p>";
  
  //emailEventAttendees(event, emailProperties);
  emailCreator(event, emailProperties);
}

/**
 * Send an email to all the guests, including the creator, no matter if attending or not
 * 
 * @param event google class CalendarEvent
 * @param emailProperties object with subject and message for the email
 */
function emailEventAttendees(event, emailProperties) {

  // Get the list of attendees including creator
  var attendees = event.getGuestList(true);
  var recipientEmails = [];

  // Collect all attendees' emails
  for (var i = 0; i < attendees.length; i++) {
    var attendee = attendees[i];
    recipientEmails.push(attendee.getEmail());
  }

  // Send the email to all recipients
  for (var j = 0; j < recipientEmails.length; j++) {
    var email = recipientEmails[j];
    GmailApp.sendEmail(email, emailProperties.subject, emailProperties.message, { htmlBody: emailProperties.message });
  }

  if (DEBUG) Logger.log("Emails sent successfully to: " + recipientEmails.join(', '));
}

/**
 * Send an email to the creator, no matter if attending or not
 * 
 * @param event google class CalendarEvent
 * @param emailProperties object with subject and message for the email
 */
function emailCreator(event, emailProperties) {

  // Get the creator
  var creatorEmail = event.getCreators()[0];

  GmailApp.sendEmail(creatorEmail, emailProperties.subject, emailProperties.message, { htmlBody: emailProperties.message });

  if (DEBUG) Logger.log("Emails sent successfully to: " + creatorEmail);
}

/**
 * Pulls the content from a template and copy it into the target agenda doc
 * 
 * @param event google class CalendarEvent
 * @param targetDocId The id of the agenda google document
 * @param topicsToProcess Array with the topics to be added as subtopics in the agenda
 */
function addMeetingNotesToDoc(event, targetDocId, topicsToProcess) {
  const targetDoc = DocumentApp.openById(targetDocId);
  const targetBody = targetDoc.getBody();

  // Index to insert elements in the doc based on the last meeting - secont title
  let index = findLastMeetingTitle(DocumentApp.ParagraphHeading.HEADING2,targetDocId)

  // Insert Title
  const formattedDate = Utilities.formatDate(event.getStartTime(),'GMT','yyyy-MM-dd');
  const titleParagraph = `${formattedDate} | ${event.getTitle()}`;
  const title = targetBody.insertParagraph(index++,titleParagraph).setHeading(DocumentApp.ParagraphHeading.HEADING2);

  insertContentToDoc(targetDocId, index, topicsToProcess)

  if (DEBUG) Logger.log(`Agenda for meeting on ${formattedDate} for ${event.getTitle()} was added`)
}

/**
 * Function to add agenda sections into the doc with formatting
 * 
 * @param targetDocId The id of the google document to be modified
 * @param posIndex The position where to start adding content
 * @param topics Array with the topics to be added as subtopics in the agenda
 */
function insertContentToDoc(targetDocId, posIndex, topics) {
  const doc = DocumentApp.openById(targetDocId);
  const body = doc.getBody();

  // Initiate the list
  const agendaList = body.insertListItem(posIndex,"");

  // Create all sections in reverse order so they stay at the top of the document
  for (let index = AGENDA_SECTIONS.length - 1; index >= 0; index--) {
    let section = AGENDA_SECTIONS[index];

    // Add one empty nesting item 
    const subitem = body.insertListItem(posIndex,"").setNestingLevel(1);

    // Add discussions items for that section
    topics.filter( item => item.section == section.title).reverse().forEach (topic => {
      const subitem = body.insertListItem(posIndex, topic.topic || " ");
      subitem.setNestingLevel(1);
    });

    //Include nesting list items
    if(section.nest) {
      section.nest.reverse().forEach(nested => {
        const subitem = body.insertListItem(posIndex, nested.title || " ");
        if (nested.url) subitem.setLinkUrl(nested.url);
        subitem.setNestingLevel(1);
      });
    }

    const item = body.insertListItem(posIndex,"");
    item.appendText(section.title + "." || " ").setBold(true).setForegroundColor(orange);
    item.appendText(" ").setBold(false).setItalic(true).setForegroundColor(black);
    item.appendText(section.description || " ");
    item.setListId(agendaList)
  }
}

/**
 * Identify the index where to start adding new notes
 * @param searchCriteria 
 * @param targetDocId 
 * @returns the index position in the doc
 */
function findLastMeetingTitle(searchCriteria, targetDocId) {
  const targetDoc = DocumentApp.openById(targetDocId);
  const body = targetDoc.getBody();
  const elements = body.getNumChildren();

  // start searching after the first element because we normally have an stack section
  for (let i = 1; i < elements; i++) {
    let item = body.getChild(i);
    if (item.getHeading() == searchCriteria) {
      return i;
    }
  }
}

/**
 * Get all calendar events in the current week
 * 
 * @param period String (current, next) defining if should get date range for this week or next week
 * @returns array of events
 */
function getWeekDates(period) {
  const now = new Date();
  let start = new Date();
  let end = new Date();
  
  if (period == 'current'){
    let day = now.getDay();
    let diff = now.getDate() - day + (day == 0 ? -6 : 1); // adjust when day is sunday
    start = new Date(now.setDate(diff));
    start.setUTCHours(0,0,0,0);
    end = new Date(start.getFullYear(), start.getMonth(), start.getDate() + 5);
  }
  
  if (period == 'next') {
    start = new Date(now.getFullYear(), now.getMonth(), now.getDate() + (7 - now.getDay()));
    start.setUTCHours(0,0,0,0);
    end = new Date(start.getFullYear(), start.getMonth(), start.getDate() + 7);
  }
  
  const number = getWeekNumber(end);

  if (DEBUG) console.log(`Dates processed for ${period} week, starting on ${start}, finishing on ${end} and number of the week ${number}`);

  return {start, end, number};
}

/**
 * Calculates the ISO 8601 week number for a given date.
 * ISO 8601 defines week 1 as the first week with at least 4 days in the new year.
 * Weeks start on Monday.
 *
 * @param {Date} date The input Date object for which to calculate the week number.
 * @returns {number} The ISO 8601 week number (1-53).
 */
function getWeekNumber(date) {
  // Create a new Date object in UTC to avoid timezone issues, and work with a copy.
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));

  // Set the date to the nearest Thursday of the current week.
  // According to ISO 8601, the week number is determined by the Thursday of that week.
  // d.getUTCDay() returns 0 for Sunday, 1 for Monday, ..., 6 for Saturday.
  // We want Monday=1, ..., Sunday=7 for ISO week calculations.
  // (d.getUTCDay() || 7) converts 0 (Sunday) to 7, and leaves 1-6 as is.
  // We then add 4 (to reach Thursday) and subtract the current adjusted day of week.
  d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay() || 7));

  // Get the first day of the year (January 1st) for the year of the adjusted Thursday.
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));

  // Calculate the difference in milliseconds between the adjusted Thursday and Jan 1st.
  const diff = d - yearStart;

  // Convert milliseconds to days: 1 day = 86,400,000 milliseconds.
  // Then calculate the week number:
  // (days_difference_from_jan1_to_thursday + 1) / 7
  // Math.ceil() is used because week numbers are integers and start from 1.
  return Math.ceil((((diff / 86400000) + 1) / 7));
}

/**
 * Filter all the events to get only those that are part of the oneToOneEvents and where the creator or the guest haven't declined
 * 
 * @param {date} startDate 
 * @param {date} endDate 
 * @param {array} oneToOneEvents 
 * @returns {array} Array of events
 */
function getEvents(startDate, endDate, oneToOneEvents) {
  const nextEvents = CalendarApp.getCalendarById(CALENDAR_ID).getEvents(startDate, endDate);

  const foundEvents = [];

  // Iterate over nextEvents and find matching agendaEvents
  for (let nextEvent of nextEvents) {
    for (let agendaEvent of oneToOneEvents) {
      if (nextEvent.getId().startsWith(agendaEvent.eventId)) {
        
        if (isCreatorDeclined(nextEvent) === true || isGuestDeclined(nextEvent) === true) {
          Logger.log(`Skiping event ${nextEvent.getTitle()} because creator or guest declined`)
          continue;
        }
        
        foundEvents.push({
          settings: agendaEvent,
          calendarEvent: nextEvent
        });
        break; // Break inner loop once a match is found
      }
    }
  }

  if (DEBUG) Logger.log(`Found ${foundEvents.length} events to process`)

  return foundEvents;
}

/**
 * Determine if the creator of an event has declined
 * @param event 
 * @returns boolean, true if declined
 */
function isCreatorDeclined(event) {
  // Get the organizer's email address
  var creatorEmail = event.getCreators()[0];

  // Get the list of attendees including creator
  var attendees = event.getGuestList(true);

  // Check the response status of the creator
  for (var i = 0; i < attendees.length; i++) {
    var attendee = attendees[i];

    if (DEBUG) console.log(`Did Creator Declined? Comparing creator: ${creatorEmail} with attendee: ${attendee.getEmail()} where attendee replied as ${attendee.getGuestStatus()}`);

    if (attendee.getEmail() === creatorEmail) {
      if (attendee.getGuestStatus() === CalendarApp.GuestStatus.YES) {
        return false; // Creator is attending
      } else if (attendee.getGuestStatus() === CalendarApp.GuestStatus.NO) {
        return true; // Creator declined
      }
    }
  }

  // If creator's status is not found, assume is attending
  return false;
}

/**
 * Determine if the guest of an event has declined
 * @param event 
 * @returns boolean, true if declined
 */
function isGuestDeclined(event) {
  // Get the list of attendees
  var attendees = event.getGuestList();

  // Check the response status of the guest that is not creator
  for (var i = 0; i < attendees.length; i++) {
    var attendee = attendees[i];

    if (DEBUG) console.log(`Did Guest Declined? Comparing attendee: ${attendee.getEmail()} where attendee replied as ${attendee.getGuestStatus()}`);

    if (attendee.getGuestStatus() === CalendarApp.GuestStatus.YES) {
      return false; // Guest is attending
    } else if (attendee.getGuestStatus() === CalendarApp.GuestStatus.NO) {
      return true; // Guest declined
    }
  }

  // If guest's status is not found, assume is attending
  return false;
}

/**
 * Get the content of a spreadsheet for agenda topics and filter based on the year and week
 * 
 * @param spreadsheetId String The spreadsheet that contains the agenda topics
 * @param yearFilter String The year that will be used to filter the content
 * @param weekFilter String The number of the week to be used to filter topics
 * 
 * @returns array with topic objects
 */
function getTopicsToProcess(spreadsheetId, yearFilter, weekFilter) {
  try {
    // Open the spreadsheet by its ID
    const spreadsheet = SpreadsheetApp.openById(spreadsheetId);

    // Get the active sheet (you might want to specify a sheet by name if there are multiple)
    const sheet = spreadsheet.getSheetByName(yearFilter);

    // Get all data from the sheet, excluding headers (assuming row 1 is headers)
    // getDataRange() gets the range containing all data.
    // getValues() gets a 2D array of all the values in the range.
    const range = sheet.getDataRange();
    const values = range.getValues();

    // Check if there's any data beyond headers
    if (values.length < 2) {
      if (DEBUG) Logger.log('No data found in the spreadsheet beyond the header row.');
      return []; // Return an empty array if only headers or no data
    }

    // Assume the first row is headers and skip it.
    // The actual data starts from the second row (index 1).
    const dataRows = values.slice(1);

    if (DEBUG) Logger.log('Data unfiltered: ' + dataRows);

    const filteredData = [];

    // Iterate over each data row and apply the filter
    dataRows.forEach(row => {
      // Ensure the row has at least 3 columns (A, B, C)
      if (row.length >= 3) {
        const section = row[0]; // Column A (index 0)
        const topic = row[1];   // Column B (index 1)
        const week = row[2];    // Column C (index 2)

        // Apply the exact match filter on the 'Week' column
        if (week && String(week).trim() === String(weekFilter).trim()) {
          filteredData.push({
            section: section,
            topic: topic,
            week: week
          });
        }
      }
    });

  if (DEBUG) Logger.log('Data filtered: ' + JSON.stringify(filteredData));
  return filteredData;

  } catch (e) {
    Logger.log('Error reading spreadsheet data: ' + e.toString());
    return []; // Return an empty array in case of an error
  }
}

/**
 * Pull data from a spreadsheet to get a map of eventId and targetDocId for each person to manage their 1:1
 * 
 * @param {string} docId  The spreadsheet id where the details for each team member event is present
 * @param {string} sheetName The sheet name where the information is present
 * @returns {array} Object {person:x, eventId:x, targetDoc:x}
 */
function getOneToOneEvents(docId, sheetName) {
  try {
    // Open the spreadsheet by its ID
    const spreadsheet = SpreadsheetApp.openById(docId);

    // Get the active sheet (you might want to specify a sheet by name if there are multiple)
    const sheet = spreadsheet.getSheetByName(sheetName);

    // Get all data from the sheet, excluding headers (assuming row 1 is headers)
    // getDataRange() gets the range containing all data.
    // getValues() gets a 2D array of all the values in the range.
    const range = sheet.getDataRange();
    const values = range.getValues();

    // Check if there's any data beyond headers
    if (values.length < 2) {
      if (DEBUG) Logger.log('No data found in the spreadsheet beyond the header row.');
      return []; // Return an empty array if only headers or no data
    }

    // Assume the first row is headers and skip it.
    // The actual data starts from the second row (index 1).
    const dataRows = values.slice(1);

    if (DEBUG) Logger.log('Data unfiltered: ' + dataRows);

    const dataObjects = [];

    // Iterate over each data row and apply the filter
    dataRows.forEach(row => {
      // Ensure the row has at least 3 columns (A, B, C)
      if (row.length >= 3) {
        const person = row[0]; // Column A (index 0)
        const eventId = row[1];   // Column B (index 1)
        const targetDoc = row[2];    // Column C (index 2)

        dataObjects.push({
          section: section,
          topic: topic,
          week: week
        });
      }
    });

  if (DEBUG) Logger.log('Data organized: ' + JSON.stringify(dataObjects));

  return dataObjects;

  } catch (e) {
    Logger.log('Error reading spreadsheet data: ' + e.toString());
    return []; // Return an empty array in case of an error
  }
}